export const COLOURS = {
  bacgroundGreen: '#8649FF',
  white: '#ffffff',
  black: '#2C2C2C',
  Textblack: '#000',
  gray: '#FCFCFC',
  grey: '#F5F5F5',
  yellow: '#f4bc1a',
  purple: '#b98ddf',
  red: '#ff0000',
  backgroundWhite: '#efefef',
};
export const Items = {
  productsDiscount: [
    {
      id: 100,
      category: 'discount',
      productName: 'MI Super Bass Bluetooth Wireless Headphones',
      productPriceDiscount: 1799000,
      productPrice: 1599000,
      description:
        'Up to 20 hours battery life | Super powerful Bass | 40mm dynamic driver | Pressure less ear muffs | Bluetooth 5.0 | Voice control',
      isOff: true,
      offPercentage: 10,
      productImage: require('../assets/images/products/Mi1.png'),
      style: 'CZ0326-100',
      ProductDetails: {
        type: 'Foam midsole',
        color: ['red', 'black', 'white'],
        size: ['S', 'M', 'L', 'XL', 'XXL'],
        hagtag: ['#giàythểthao', '#giàynam', '#giàygym'],
        brand: 'boAt',
        origin: 'USA',
        Benefits: [
          'ZinShoes Store cam kết cung cấp sản phẩm chính hãng đến tay người dùng khi mua hàng.',
          'Chúng tôi cam kết đổi trả sản phẩm nếu quý khách hàng không hài lòng với chất lượng sản phẩm hoặc kích cỡ không phù hợp.',
          'Để đảm bảo quyền lợi cho khách hàng, chúng tôi cam kết bảo mật thông tin cá nhân và đặt hàng an toàn, tiện lợi qua app.',
        ],
      },

      isAvailable: true,
      productImageList: [
        require('../assets/images/products/Mi1.png'),
        require('../assets/images/products/Mi2.png'),
        require('../assets/images/products/Mi3.png'),
      ],
    },
    {
      id: 101,
      category: 'discount',
      productName: 'boAt Rockerz 450 Bluetooth Headphone',
      productPriceDiscount: 1499000,
      productPrice: 1199000,
      description:
        'boAt Rockerz 450 M is an on-ear wireless headset that has been ergonomically designed to meet the needs of music lovers.',
      isOff: true,
      offPercentage: 15,
      productImage: require('../assets/images/products/boat1.png'),
      style: 'CZ0326-100',
      ProductDetails: {
        type: 'Foam midsole',
        color: ['red', 'black', 'white'],
        size: ['S', 'M', 'L', 'XL', 'XXL'],
        hagtag: ['#giàythểthao', '#giàynam', '#giàygym'],
        brand: 'boAt',
        origin: 'USA',
        Benefits: [
          'ZinShoes Store cam kết cung cấp sản phẩm chính hãng đến tay người dùng khi mua hàng.',
          'Chúng tôi cam kết đổi trả sản phẩm nếu quý khách hàng không hài lòng với chất lượng sản phẩm hoặc kích cỡ không phù hợp.',
          'Để đảm bảo quyền lợi cho khách hàng, chúng tôi cam kết bảo mật thông tin cá nhân và đặt hàng an toàn, tiện lợi qua app.',
        ],
      },
      isAvailable: true,
      productImageList: [
        require('../assets/images/products/boat1.png'),
        require('../assets/images/products/boat2.png'),
        require('../assets/images/products/boat3.png'),
      ],
    },
    {
      id: 102,
      category: 'discount',
      productName: 'MI Super Bass Bluetooth Wireless Headphones',
      productPriceDiscount: 1799000,
      productPrice: 1599000,
      description:
        'Up to 20 hours battery life | Super powerful Bass | 40mm dynamic driver | Pressure less ear muffs | Bluetooth 5.0 | Voice control',
      isOff: true,
      offPercentage: 10,
      productImage: require('../assets/images/products/Mi1.png'),
      style: 'CZ0326-100',
      ProductDetails: {
        type: 'Foam midsole',
        color: ['red', 'black', 'white'],
        size: ['S', 'M', 'L', 'XL', 'XXL'],
        hagtag: ['#giàythểthao', '#giàynam', '#giàygym'],
        brand: 'boAt',
        origin: 'USA',
        Benefits: [
          'ZinShoes Store cam kết cung cấp sản phẩm chính hãng đến tay người dùng khi mua hàng.',
          'Chúng tôi cam kết đổi trả sản phẩm nếu quý khách hàng không hài lòng với chất lượng sản phẩm hoặc kích cỡ không phù hợp.',
          'Để đảm bảo quyền lợi cho khách hàng, chúng tôi cam kết bảo mật thông tin cá nhân và đặt hàng an toàn, tiện lợi qua app.',
        ],
      },
      isAvailable: true,
      productImageList: [
        require('../assets/images/products/Mi1.png'),
        require('../assets/images/products/Mi2.png'),
        require('../assets/images/products/Mi3.png'),
      ],
    },
    {
      id: 103,
      category: 'discount',
      productName: 'boAt Rockerz 450 Bluetooth Headphone',
      productPriceDiscount: 1499000,
      productPrice: 1199000,
      description:
        'boAt Rockerz 450 M is an on-ear wireless headset that has been ergonomically designed to meet the needs of music lovers.',
      isOff: true,
      offPercentage: 15,
      productImage: require('../assets/images/products/boat1.png'),
      style: 'CZ0326-100',
      ProductDetails: {
        type: 'Foam midsole',
        color: ['red', 'black', 'white'],
        size: ['S', 'M', 'L', 'XL', 'XXL'],
        hagtag: ['#giàythểthao', '#giàynam', '#giàygym'],
        brand: 'boAt',
        origin: 'USA',
        Benefits: [
          'ZinShoes Store cam kết cung cấp sản phẩm chính hãng đến tay người dùng khi mua hàng.',
          'Chúng tôi cam kết đổi trả sản phẩm nếu quý khách hàng không hài lòng với chất lượng sản phẩm hoặc kích cỡ không phù hợp.',
          'Để đảm bảo quyền lợi cho khách hàng, chúng tôi cam kết bảo mật thông tin cá nhân và đặt hàng an toàn, tiện lợi qua app.',
        ],
      },
      isAvailable: true,
      productImageList: [
        require('../assets/images/products/boat1.png'),
        require('../assets/images/products/boat2.png'),
        require('../assets/images/products/boat3.png'),
      ],
    },
    {
      id: 104,
      category: 'discount',
      productName: 'MI Super Bass Bluetooth Wireless Headphones',
      productPriceDiscount: 1799000,
      productPrice: 1599000,
      description:
        'Up to 20 hours battery life | Super powerful Bass | 40mm dynamic driver | Pressure less ear muffs | Bluetooth 5.0 | Voice control',
      isOff: true,
      offPercentage: 10,
      productImage: require('../assets/images/products/Mi1.png'),
      style: 'CZ0326-100',
      ProductDetails: {
        type: 'Foam midsole',
        color: ['red', 'black', 'white'],
        size: ['S', 'M', 'L', 'XL', 'XXL'],
        hagtag: ['#giàythểthao', '#giàynam', '#giàygym'],
        brand: 'boAt',
        origin: 'USA',
        Benefits: [
          'ZinShoes Store cam kết cung cấp sản phẩm chính hãng đến tay người dùng khi mua hàng.',
          'Chúng tôi cam kết đổi trả sản phẩm nếu quý khách hàng không hài lòng với chất lượng sản phẩm hoặc kích cỡ không phù hợp.',
          'Để đảm bảo quyền lợi cho khách hàng, chúng tôi cam kết bảo mật thông tin cá nhân và đặt hàng an toàn, tiện lợi qua app.',
        ],
      },
      isAvailable: true,
      productImageList: [
        require('../assets/images/products/Mi1.png'),
        require('../assets/images/products/Mi2.png'),
        require('../assets/images/products/Mi3.png'),
      ],
    },
    ,
    {
      id: 105,
      category: 'discount',
      productName: 'boAt Rockerz 450 Bluetooth Headphone',
      productPriceDiscount: 1499000,
      productPrice: 1199000,
      description:
        'boAt Rockerz 450 M is an on-ear wireless headset that has been ergonomically designed to meet the needs of music lovers.',
      isOff: true,
      offPercentage: 15,
      productImage: require('../assets/images/products/boat1.png'),
      style: 'CZ0326-100',
      ProductDetails: {
        type: 'Foam midsole',
        color: ['red', 'black', 'white'],
        size: ['S', 'M', 'L', 'XL', 'XXL'],
        hagtag: ['#giàythểthao', '#giàynam', '#giàygym'],
        brand: 'boAt',
        origin: 'USA',
        Benefits: [
          'ZinShoes Store cam kết cung cấp sản phẩm chính hãng đến tay người dùng khi mua hàng.',
          'Chúng tôi cam kết đổi trả sản phẩm nếu quý khách hàng không hài lòng với chất lượng sản phẩm hoặc kích cỡ không phù hợp.',
          'Để đảm bảo quyền lợi cho khách hàng, chúng tôi cam kết bảo mật thông tin cá nhân và đặt hàng an toàn, tiện lợi qua app.',
        ],
      },
      isAvailable: true,
      productImageList: [
        require('../assets/images/products/boat1.png'),
        require('../assets/images/products/boat2.png'),
        require('../assets/images/products/boat3.png'),
      ],
    },
  ],
  products: [
    {
      id: 1,
      category: 'product',
      productName: 'boAt Airdopes 441',
      productPrice: 1999000,
      description:
        'Bluetooth: It has Bluetooth v5.0 with a range of 10m and is compatible with Android & iOS',
      isOff: true,
      offPercentage: 18,
      productImage: require('../assets/images/accessories/boatairpods1.png'),
      style: 'CZ0326-100',
      ProductDetails: {
        type: 'Foam midsole',
        color: ['red', 'black', 'white'],
        size: ['S', 'M', 'L', 'XL', 'XXL'],
        hagtag: ['#giàythểthao', '#giàynam', '#giàygym'],
        brand: 'boAt',
        origin: 'USA',
        Benefits: [
          'ZinShoes Store cam kết cung cấp sản phẩm chính hãng đến tay người dùng khi mua hàng.',
          'Chúng tôi cam kết đổi trả sản phẩm nếu quý khách hàng không hài lòng với chất lượng sản phẩm hoặc kích cỡ không phù hợp.',
          'Để đảm bảo quyền lợi cho khách hàng, chúng tôi cam kết bảo mật thông tin cá nhân và đặt hàng an toàn, tiện lợi qua app.',
        ],
      },
      isAvailable: true,
      productImageList: [
        require('../assets/images/accessories/boatairpods1.png'),
        require('../assets/images/accessories/boatairpods2.png'),
        require('../assets/images/accessories/boatairpods3.png'),
      ],
    },
    {
      id: 2,
      category: 'product',
      productName: 'boAt Bassheads 242',
      productPrice: 399000,
      description:
        'Fly into your workouts with precise tones that inspire and energize your system with its HD sound, all the time.',
      isOff: false,
      productImage: require('../assets/images/accessories/boatbassheads1.png'),
      style: 'CZ0326-100',
      ProductDetails: {
        type: 'Foam midsole',
        color: ['red', 'black', 'white'],
        size: ['S', 'M', 'L', 'XL', 'XXL'],
        hagtag: ['#giàythểthao', '#giàynam', '#giàygym'],
        brand: 'boAt',
        origin: 'USA',
        Benefits: [
          'ZinShoes Store cam kết cung cấp sản phẩm chính hãng đến tay người dùng khi mua hàng.',
          'Chúng tôi cam kết đổi trả sản phẩm nếu quý khách hàng không hài lòng với chất lượng sản phẩm hoặc kích cỡ không phù hợp.',
          'Để đảm bảo quyền lợi cho khách hàng, chúng tôi cam kết bảo mật thông tin cá nhân và đặt hàng an toàn, tiện lợi qua app.',
        ],
      },
      isAvailable: true,
      productImageList: [
        require('../assets/images/accessories/boatbassheads1.png'),
        require('../assets/images/accessories/boatbassheads2.png'),
        require('../assets/images/accessories/boatbassheads3.png'),
      ],
    },
    {
      id: 3,
      category: 'product',
      productName: 'boAt Rockerz 255 Pro+',
      productPrice: 1499000,
      description:
        'The unbeatable boAt signature sound shines through no matter what are you playing courtesy its 10mm drivers.',
      isOff: false,
      productImage: require('../assets/images/accessories/boatrockerz1.png'),
      style: 'CZ0326-100',
      ProductDetails: {
        type: 'Foam midsole',
        color: ['red', 'black', 'white'],
        size: ['S', 'M', 'L', 'XL', 'XXL'],
        hagtag: ['#giàythểthao', '#giàynam', '#giàygym'],
        brand: 'boAt',
        origin: 'USA',
        Benefits: [
          'ZinShoes Store cam kết cung cấp sản phẩm chính hãng đến tay người dùng khi mua hàng.',
          'Chúng tôi cam kết đổi trả sản phẩm nếu quý khách hàng không hài lòng với chất lượng sản phẩm hoặc kích cỡ không phù hợp.',
          'Để đảm bảo quyền lợi cho khách hàng, chúng tôi cam kết bảo mật thông tin cá nhân và đặt hàng an toàn, tiện lợi qua app.',
        ],
      },
      isAvailable: false,
      productImageList: [
        require('../assets/images/accessories/boatrockerz1.png'),
        require('../assets/images/accessories/boatrockerz2.png'),
        require('../assets/images/accessories/boatrockerz3.png'),
      ],
    },
    {
      id: 4,
      category: 'product',
      productName: 'Boult Audio AirBass Propods TWS',
      productPrice: 1299000,
      description:
        'One Touch Control & Voice Assistant: With one multifunction button, you can play/pause, previous/next track and answer/hang-up calls.Voice assistant function lets you access siri/Google Assistant',
      isOff: false,
      productImage: require('../assets/images/accessories/boultairbass1.png'),
      style: 'CZ0326-100',
      ProductDetails: {
        type: 'Foam midsole',
        color: ['red', 'black', 'white'],
        size: ['S', 'M', 'L', 'XL', 'XXL'],
        hagtag: ['#giàythểthao', '#giàynam', '#giàygym'],
        brand: 'boAt',
        origin: 'USA',
        Benefits: [
          'ZinShoes Store cam kết cung cấp sản phẩm chính hãng đến tay người dùng khi mua hàng.',
          'Chúng tôi cam kết đổi trả sản phẩm nếu quý khách hàng không hài lòng với chất lượng sản phẩm hoặc kích cỡ không phù hợp.',
          'Để đảm bảo quyền lợi cho khách hàng, chúng tôi cam kết bảo mật thông tin cá nhân và đặt hàng an toàn, tiện lợi qua app.',
        ],
      },
      isAvailable: true,
      productImageList: [
        require('../assets/images/accessories/boultairbass1.png'),
        require('../assets/images/accessories/boultairbass2.png'),
        require('../assets/images/accessories/boultairbass3.png'),
      ],
    },
    {
      id: 5,
      category: 'product',
      productName: 'Boult Audio AirBass Propods TWS',
      productPrice: 1299000,
      description:
        'One Touch Control & Voice Assistant: With one multifunction button, you can play/pause, previous/next track and answer/hang-up calls.Voice assistant function lets you access siri/Google Assistant',
      isOff: false,
      productImage: require('../assets/images/accessories/boultairbass1.png'),
      style: 'CZ0326-100',
      ProductDetails: {
        type: 'Foam midsole',
        color: ['red', 'black', 'white'],
        size: ['S', 'M', 'L', 'XL', 'XXL'],
        hagtag: ['#giàythểthao', '#giàynam', '#giàygym'],
        brand: 'boAt',
        origin: 'USA',
        Benefits: [
          'ZinShoes Store cam kết cung cấp sản phẩm chính hãng đến tay người dùng khi mua hàng.',
          'Chúng tôi cam kết đổi trả sản phẩm nếu quý khách hàng không hài lòng với chất lượng sản phẩm hoặc kích cỡ không phù hợp.',
          'Để đảm bảo quyền lợi cho khách hàng, chúng tôi cam kết bảo mật thông tin cá nhân và đặt hàng an toàn, tiện lợi qua app.',
        ],
      },
      isAvailable: true,
      productImageList: [
        require('../assets/images/accessories/boultairbass1.png'),
        require('../assets/images/accessories/boultairbass2.png'),
        require('../assets/images/accessories/boultairbass3.png'),
      ],
    },
    {
      id: 6,
      category: 'product',
      productName: 'Boult Audio AirBass Propods TWS',
      productPrice: 1299000,
      description:
        'One Touch Control & Voice Assistant: With one multifunction button, you can play/pause, previous/next track and answer/hang-up calls.Voice assistant function lets you access siri/Google Assistant',
      isOff: false,
      productImage: require('../assets/images/accessories/boultairbass1.png'),
      style: 'CZ0326-100',
      ProductDetails: {
        type: 'Foam midsole',
        color: ['red', 'black', 'white'],
        size: ['S', 'M', 'L', 'XL', 'XXL'],
        hagtag: ['#giàythểthao', '#giàynam', '#giàygym'],
        brand: 'boAt',
        origin: 'USA',
        Benefits: [
          'ZinShoes Store cam kết cung cấp sản phẩm chính hãng đến tay người dùng khi mua hàng.',
          'Chúng tôi cam kết đổi trả sản phẩm nếu quý khách hàng không hài lòng với chất lượng sản phẩm hoặc kích cỡ không phù hợp.',
          'Để đảm bảo quyền lợi cho khách hàng, chúng tôi cam kết bảo mật thông tin cá nhân và đặt hàng an toàn, tiện lợi qua app.',
        ],
      },
      isAvailable: true,
      productImageList: [
        require('../assets/images/accessories/boultairbass1.png'),
        require('../assets/images/accessories/boultairbass2.png'),
        require('../assets/images/accessories/boultairbass3.png'),
      ],
    },
  ],
};

export const Review = [
  {
    id: 1,
    name: 'Nguyễn Văn A',
    avatar: require('../assets/images/avatar/avatar1.jpeg'),
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    item: 'Nike air force 1',
    rating: 5,
    date: '01/01/2021',
    isActive: true,
  },
  {
    id: 2,
    name: 'Nguyễn Văn B',
    avatar: require('../assets/images/avatar/avatar2.jpeg'),
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    item: 'Nike air force 1',
    rating: 4,
    date: '01/01/2021',
    isActive: false,
  },
  {
    id: 3,
    name: 'Nguyễn Văn C',
    avatar: require('../assets/images/avatar/avatar3.jpeg'),
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    item: 'Nike air force 1',
    rating: 3,
    date: '01/01/2021',
    isActive: true,
  },
  {
    id: 4,
    name: 'Nguyễn Văn D',
    avatar: require('../assets/images/avatar/avatar4.jpeg'),
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    item: 'Nike air force 1',
    rating: 2,
    date: '01/01/2021',
    isActive: true,
  },
  {
    id: 5,
    name: 'Nguyễn Văn E',
    avatar: require('../assets/images/avatar/avatar5.jpeg'),
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    item: 'Nike air force 1',
    rating: 1,
    date: '01/01/2021',
    isActive: true,
  },
];
